const key = 'smart-cpgrams-tickets-v2'
const demoRoute = { department: 'Public Works Department', team: 'Road Maintenance', category: 'Roads & footpaths', confidence: 91, reason: 'Matched road-maintenance keywords.' }
const demoLocation = { latitude: 28.6139, longitude: 77.2090, label: 'Near Ward 12 Community Hall, Delhi' }
function demoTicket(id, complaint, status, createdAt, officerUpdate) {
  const timeline = [
    { label: 'Complaint submitted', detail: 'Your report was securely recorded.', time: createdAt, state: 'done' },
    { label: 'Assigned to department', detail: `${demoRoute.department} · ${demoRoute.team}`, time: createdAt, state: status === 'Submitted' ? 'future' : 'done' },
    { label: officerUpdate ? 'Officer work update submitted' : 'Department response due', detail: officerUpdate ? 'A field photo is ready for your verification.' : 'Automatic escalation begins if there is no update.', time: officerUpdate?.createdAt || '2026-08-24T09:00:00Z', state: officerUpdate || status === 'In progress' ? 'active' : 'future' },
    { label: status === 'Resolved' ? 'Resolution accepted by citizen' : 'Resolution target', detail: status === 'Resolved' ? 'You confirmed the work at the reported location.' : 'You will be asked to confirm the outcome.', time: status === 'Resolved' ? '2026-08-22T16:00:00Z' : '2026-08-27T00:00:00Z', state: status === 'Resolved' ? 'done' : 'future' }
  ]
  return { id, complaint, location: demoLocation, route: demoRoute, status, createdAt, escalationAt: '2026-08-25T09:00:00Z', dueAt: '2026-08-27T00:00:00Z', escalationLevel: 0, currentAuthority: 'Ward Officer · Ward 12', communityCount: status === 'Pending verification' ? 3 : undefined, communityComplaint: status === 'Pending verification', officerUpdate, statusHistory: [{ oldStatus: null, newStatus: status, changedBy: 'system', timestamp: createdAt, reason: 'Seeded demonstration record' }], timeline }
}
const demoTickets = [
  demoTicket('SCG-2026-004821', 'The pothole outside Ward 12 Community Hall has caused two accidents.', 'Pending verification', '2026-08-23T09:12:00Z', { officerName: 'Ramesh Kumar · Ward Officer', note: 'Road surface repaired and debris cleared. Please verify the site photo.', photoDataUrl: 'https://images.unsplash.com/photo-1517089596392-fb9a9033e05c?auto=format&fit=crop&w=900&q=80', location: { ...demoLocation, label: 'Ward 12 Community Hall · 28.613900, 77.209000' }, capturedAt: '2026-08-22T11:28:00Z', originalFileName: 'ward-12-repair.jpg', createdAt: '2026-08-22T11:30:00Z' }),
  demoTicket('SCG-2026-004792', 'A streetlight near the bus stop has not worked for three nights.', 'In progress', '2026-08-19T18:45:00Z'),
  demoTicket('SCG-2026-004731', 'Water is leaking from the public pipeline beside our lane.', 'Submitted', '2026-08-18T07:20:00Z'),
  demoTicket('SCG-2026-004510', 'The footpath outside the school was repaired last month.', 'Resolved', '2026-08-05T10:05:00Z')
]
function read() { try { const stored = localStorage.getItem(key); const tickets = stored ? JSON.parse(stored) : []; if (!tickets.length) { write(demoTickets); return demoTickets } return tickets } catch { return demoTickets } }
function write(tickets) { localStorage.setItem(key, JSON.stringify(tickets)) }
const escalationPath = ['Ward Officer · Ward 12', 'Supervisor · Public Works Department', 'Nodal Officer · Municipal Grievance Cell']
function applySlaEscalation(tickets) {
  const now = Date.now(); let changed = false
  const updated = tickets.map(ticket => { if (ticket.status === 'Resolved' || ticket.status === 'Pending verification' || now < new Date(ticket.escalationAt).getTime()) return ticket; const level = ticket.escalationLevel || 0; if (level >= escalationPath.length - 1) return ticket; const nextLevel = level + 1; const nextAuthority = escalationPath[nextLevel]; const timestamp = new Date().toISOString(); changed = true; return { ...ticket, status: 'Escalated', escalationLevel: nextLevel, currentAuthority: nextAuthority, escalations: [...(ticket.escalations || []), { level: nextLevel, from: escalationPath[level], to: nextAuthority, timestamp, reason: 'SLA deadline exceeded' }], statusHistory: [...(ticket.statusHistory || []), { oldStatus: ticket.status, newStatus: 'Escalated', changedBy: 'sla-engine', timestamp, reason: 'SLA deadline exceeded' }], timeline: [...ticket.timeline, { label: 'Automatically escalated', detail: `SLA exceeded. Assigned to ${nextAuthority}.`, time: timestamp, state: 'active' }] } })
  if (changed) write(updated)
  return updated
}
export async function getTickets() { await new Promise(resolve => setTimeout(resolve, 100)); return applySlaEscalation(read()) }
function distanceMetres(first, second) { const earthRadius = 6371000; const latDelta = (second.latitude - first.latitude) * Math.PI / 180; const lngDelta = (second.longitude - first.longitude) * Math.PI / 180; const a = Math.sin(latDelta / 2) ** 2 + Math.cos(first.latitude * Math.PI / 180) * Math.cos(second.latitude * Math.PI / 180) * Math.sin(lngDelta / 2) ** 2; return earthRadius * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)) }
export async function createTicket(input) { await new Promise(resolve => setTimeout(resolve, 350)); const now = new Date(); const escalation = new Date(now.getTime() + 48 * 60 * 60 * 1000); const due = new Date(now.getTime() + 72 * 60 * 60 * 1000); const id = `SCG-${now.getFullYear()}-${String(Math.floor(100000 + Math.random() * 899999))}`; const existing = read(); const parent = existing.find(candidate => !candidate.clusterParentId && candidate.status !== 'Resolved' && candidate.route.category === input.route.category && distanceMetres(candidate.location, input.location) <= 100 && Math.abs(now.getTime() - new Date(candidate.createdAt).getTime()) <= 48 * 60 * 60 * 1000); const ticket = { id, complaint: input.complaint, location: input.location, route: input.route, status: 'Assigned', createdAt: now.toISOString(), escalationAt: escalation.toISOString(), dueAt: due.toISOString(), escalationLevel: 0, currentAuthority: 'Ward Officer · Ward 12', clusterParentId: parent?.id, statusHistory: [{ oldStatus: null, newStatus: 'Assigned', changedBy: 'system', timestamp: now.toISOString(), reason: 'Complaint classified and routed' }], timeline: [{ label: 'Complaint submitted', detail: 'Your report was securely recorded.', time: now.toISOString(), state: 'done' }, { label: parent ? 'Joined a community complaint' : 'Assigned to department', detail: parent ? `Matched with nearby reports under ${parent.id}.` : `${input.route.department} · ${input.route.team}`, time: now.toISOString(), state: 'active' }, { label: 'Department response due', detail: 'Automatic escalation begins if there is no update.', time: escalation.toISOString(), state: 'future' }, { label: 'Resolution target', detail: 'You will be asked to confirm the outcome.', time: due.toISOString(), state: 'future' }] }; if (!parent) { write([ticket, ...existing]); return { ticket } }; const nearbyCount = (parent.communityCount || 1) + 1; const updatedParent = { ...parent, communityCount: nearbyCount, communityComplaint: true, clusterChildIds: [...(parent.clusterChildIds || []), ticket.id], timeline: [...parent.timeline, { label: 'Community complaint updated', detail: `${nearbyCount} nearby reports are now grouped into this parent case.`, time: now.toISOString(), state: 'active' }] }; write([ticket, ...existing.map(candidate => candidate.id === parent.id ? updatedParent : candidate)]); return { ticket, duplicateMatch: { parentId: parent.id, nearbyCount, parentComplaint: parent.complaint, distanceMetres: Math.round(distanceMetres(parent.location, input.location)) } }
}
export async function getTicket(id) { await new Promise(resolve => setTimeout(resolve, 160)); return applySlaEscalation(read()).find(ticket => ticket.id.toLowerCase() === id.trim().toLowerCase()) }
export async function getOfficerTicket(id) { await new Promise(resolve => setTimeout(resolve, 160)); const tickets = applySlaEscalation(read()); const ticket = tickets.find(candidate => candidate.id.toLowerCase() === id.trim().toLowerCase()); return ticket?.clusterParentId ? tickets.find(candidate => candidate.id === ticket.clusterParentId) : ticket }
export async function getOfficerTickets() { await new Promise(resolve => setTimeout(resolve, 120)); return applySlaEscalation(read()).filter(ticket => ticket.currentAuthority?.includes('Ward Officer')).sort((first, second) => new Date(second.createdAt) - new Date(first.createdAt)) }
export async function addOfficerUpdate(id, update) { await new Promise(resolve => setTimeout(resolve, 250)); const createdAt = new Date().toISOString(); let saved; const tickets = read().map(ticket => { if (ticket.id !== id) return ticket; const next = { ...ticket, status: 'Pending verification', officerUpdate: { ...update, createdAt }, timeline: [...ticket.timeline.map(event => event.state === 'active' ? { ...event, state: 'done' } : event), { label: 'Officer work update submitted', detail: `${update.officerName} attached a geotagged completion photo. Awaiting citizen verification.`, time: createdAt, state: 'active' }] }; saved = next; return next }); write(tickets); return saved }
export async function verifyOfficerUpdate(id, decision) { await new Promise(resolve => setTimeout(resolve, 180)); const createdAt = new Date().toISOString(); let saved; const tickets = read().map(ticket => { if (ticket.id !== id) return ticket; const accepted = decision === 'accepted'; const next = { ...ticket, status: accepted ? 'Resolved' : 'In progress', citizenVerification: { decision, createdAt }, timeline: [...ticket.timeline.map(event => event.state === 'active' ? { ...event, state: 'done' } : event), { label: accepted ? 'Resolution accepted by citizen' : 'Resolution rejected by citizen', detail: accepted ? 'The complaint has been closed with the citizen’s confirmation.' : 'The complaint has been reopened and returned to the department.', time: createdAt, state: 'active' }] }; saved = next; return next }); write(tickets); return saved }
